{
                "id": 5,
                "slug": "17145999333740063436OqK",
                "name": "Financial Economist (Sydney/Tokyo sessions)",
                "company_slug": "17141578565800063436Shz",
                "contact_slug": "17141578576010063436uPJ",
                "secondary_contact_slugs": null,
                "note_for_candidates": "",
                "number_of_openings": 1,
                "minimum_experience": 3,
                "maximum_experience": 10,
                "min_annual_salary": 75000,
                "max_annual_salary": 110000,
                "salary_type": {
                    "id": 2,
                    "label": "Annual Salary"
                },
                "job_status": {
                    "id": 1,
                    "label": "Open"
                },
                "job_status_comment": "[{\"status_id\":1,\"remark\":\"\",\"updated_by\":\"Richard Schmid\",\"updated_on\":1714599934,\"status_label\":\"Open\"},{\"status_id\":1,\"remark\":\"\",\"updated_by\":\"Richard Schmid\",\"updated_on\":1720635300,\"status_label\":\"Open\"},{\"status_id\":1,\"remark\":\"\",\"updated_by\":\"Richard Schmid\",\"updated_on\":1720635419,\"status_label\":\"Open\"},{\"status_id\":1,\"remark\":\"\",\"updated_by\":\"Richard Schmid\",\"updated_on\":1720642371,\"status_label\":\"Open\"}]",
                "latitude": "0",
                "longitude": "0",
                "city": "Tampa",
                "locality": "Tampa, FL",
                "state": "FL",
                "country": "United States",
                "address": "100 N Tampa St\nSuite 1935\nTampa, FL 33602",
                "created_on": "2024-05-01T21:45:33.000000Z",
                "created_by": 63436,
                "updated_on": "2024-07-10T20:12:51.000000Z",
                "updated_by": 63436,
                "owner": 63436,
                "enable_job_application_form": 1,
                "job_posting_status": 0,
                "job_code": null,
                "show_company_logo": 0,
                "specialization": "",
                "qualification_id": 0,
                "currency_id": 124,
                "job_description_text": "<p><u><span style=\"font-family:Arial,Helvetica,sans-serif;\">Introduction</span></u></p>\n\n<p><span style=\"font-family:Arial,Helvetica,sans-serif;\">Fair Economy operates multiple websites that provide high-quality information about forex, commodities, crypto, and macroeconomics. Our flagship site,&nbsp;<a href=\"https://www.forexfactory.com/\">Forex Factory</a>, is used by a global audience of over 4.5 million traders every month, making it one of the most visited financial websites on the internet. Traders rely on us to deliver immediate economic data, relevant breaking news stories, accurate price data, and engaging market discussion.</span></p>\n\n<p><span style=\"font-family:Arial,Helvetica,sans-serif;\">Best described as a blend of Wall Street and Silicon Valley, we take pride our commitment to delivering a high-quality product and continued investment in our team. Named as Tampa&#39;s #1 Small Business Best Places to Work in 2023, we provide an exceptional benefits package, generous compensation, and a spacious, state-of-the-art environment in the heart of downtown Tampa.</span></p>\n\n<p><u><span style=\"font-family:Arial,Helvetica,sans-serif;\">About the Role</span></u></p>\n\n<p><span style=\"font-family:Arial,Helvetica,sans-serif;\">We are looking for someone passionate about the markets and technology to join our team of Financial Economists. The team is constantly immersed in finance, trading, and economics, all while managing one of the most advanced websites of its kind. As a member of the team, you&#39;ll work in our downtown Tampa headquarters during the Sydney and Tokyo sessions (~5pm-2am), managing the day-to-day operations of our portfolio of websites, which are relied upon by our audience all over the globe.</span></p>\n\n<p><span style=\"font-family:Arial,Helvetica,sans-serif;\">As a Financial Economist, you will be expected to...</span></p>\n\n<ul>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">monitor the global financial markets</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">break market-moving news</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">post macroeconomic data as it&#39;s released</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">curate relevant, high-quality financial articles</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">officiate trader forums and members</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">ensure uptime of our data feeds and web applications</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">determine fundamental drivers for relevant asset classes</span></li>\n</ul>\n\n<p><u><span style=\"font-family:Arial,Helvetica,sans-serif;\">About the Candidate</span></u></p>\n\n<p><span style=\"font-family:Arial,Helvetica,sans-serif;\">We are searching for a brilliant financial professional who has several years experience obsessing over the markets and the internet.</span></p>\n\n<p><span style=\"font-family:Arial,Helvetica,sans-serif;\">Our ideal match is...</span></p>\n\n<ul>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">passionate about finance, economics, and technology</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">an internet and computer power-user</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">one who thrives in a collaborative team environment</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">able to cover the Tokyo and Sydney sessions</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">a college graduate with a concentration in Finance, Economics, or similar</span></li>\n</ul>\n\n<p><u><span style=\"font-family:Arial,Helvetica,sans-serif;\">Compensation</span></u></p>\n\n<ul>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Salary: $75-100K starting + premium</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Free meal every day and endless healthy snacks</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Equal-shared access to our Tampa Bay Lightning suite</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">401K, including company-funded $5K per annum</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Family health, dental, and vision insurance</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Unlimited PTO</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Professional development reimbursement</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Gym membership</span></li>\n\t<li><span style=\"font-family:Arial,Helvetica,sans-serif;\">Parking</span></li>\n</ul>",
                "job_description_file": "",
                "job_questions": [],
                "custom_fields": [],
                "resource_url": "https://app.recruitcrm.io/job/17145999333740063436OqK",
                "application_form_url": "https://recruitcrm.io/apply/17145999333740063436OqK",
                "shared_job_image": "https://production-recruitcrm-virginia.s3.amazonaws.com/41867/account/Fair_Economy/sharejobimage?updatedonParam=1714159658944,fair_economy_logo.png",
                "job_skill": "",
                "job_type": "Full Time",
                "job_category": "Finance",
                "hiring_pipeline_id": 0,
                "collaborator_users": [],
                "collaborator_teams": []
            }
